services:
  app:
    image: amazoncorretto:17-alpine
    ports:
      - 8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ticket_platform?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: ticket_platform
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
volumes:
  mysql_data: null
