# Start with a base image containing Java runtime
FROM amazoncorretto:17-alpine

# Add Maintainer Info
LABEL maintainer="rmdmohan27@gmail.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=target/Tciketing-MS-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} ticket-app.jar

COPY ${JAR_FILE} ticket-app.jar


# Run the jar file
ENTRYPOINT ["java","-jar","/ticket-app.jar"]