FROM amazoncorretto:17-alpine
LABEL maintainer="rmdmohan27@gmail.com"

# Install netcat for MySQL check
RUN apk add --no-cache netcat-openbsd

VOLUME /tmp
WORKDIR /app
EXPOSE 8089

# Specify the JAR file and copy it
ARG JAR_FILE=target/Tciketing-MS-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} ticket-app.jar

# Wait for MySQL and then start the Spring Boot app
ENTRYPOINT sh -c "\
  echo 'Waiting for MySQL, Redis, and ML Model API...'; \
  while ! nc -z mysql 3306 || ! nc -z ml-model 5000 || ! nc -z redis 6379; do sleep 2; done; \
  echo 'All services are up! Starting Spring Boot app...'; \
  exec java -jar ticket-app.jar --host=0.0.0.0 --port=8089"

